name: personal-safety
domains:
  - domain: alert.ozintel.com.au
    type: PRIMARY
services:
  - name: web
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    git:
      repo_clone_url: https://github.com/MattQuade/personal-safety.git
      branch: main