name: personal-safety
region: syd
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: MattQuade/personal-safety
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: personal-safety
    routes:
      - path: /
    run_command: npm start
    build_command: npx prisma generate && npm run build
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${safety-db.DATABASE_URL}
databases:
  - engine: PG
    name: safety-db
    version: "16"
    production: false