name: personal-safety
region: syd

databases:
  - engine: PG
    name: safety-db
    version: "16"

services:
  - name: personal-safety
    environment_slug: node-js
    github:
      repo: MattQuade/personal-safety
      branch: main
      deploy_on_push: true
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${safety-db.DATABASE_URL}

ingress:
  rules:
    - component:
        name: personal-safety
      match:
        path:
          prefix: /